import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class KobiProfileService {
  fakeBusinesses: any = [
    {
      id: 1,
      name: "Lezzetli Gıdalar Ltd.",
      sektor: 1,
      category: "Gıda",
      tp: 1,
      ify: 1,
      company: "Lezzetli Gıdalar Ltd.",
      nace_kodu: 2,
      tedarikci_tipi: 4,
      gtip: 16,
      yakinlik: 3,
      chart: true,
      group: true,
      users: false,
      pin: true,
      call: {id:1, title:'Endüstriyel Aktif Gürültü Kontrolü/Engelleme Sistemi',
      badget:'Enerji ',badgetColor:'#27ae60',tags:'#ActiveNoiceCanelling #ANC #GürültüEngelleme #GürültüKontrolü',
      url:[
        {name:'Özel Sorun/İhtiyaç/Fırsat Alanı'},
        {name:'Teknoloji Tedarikçisinden Beklentisi'},
        {name:'Aradığı Teknoloji Tedarikçisi Özellikleri'},
        {name:'Teknoloji Tedarikçisi Öncelikli Seçim Kriteri'},
      ]
    },
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 4,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Gıda",
          description:
            "Lezzetli Gıdalar Ltd., kaliteli gıda ürünleri sunarak müşterilerine hizmet vermektedir.",
        },
      ],
    },
    {
      id: 2,
      name: "İnşaat Malzemeleri AŞ",
      sektor: 2,
      category: "İnşaat",
      tp: 2,
      ify: 2,
      company: "İnşaat Malzemeleri AŞ",
      nace_kodu: 4,
      tedarikci_tipi: 3,
      gtip: 8,
      yakinlik: 5,
      chart: false,
      group: false,
      users: true,
      pin: true,
      cagri:{id:2, title:'Kozmetik Teknoloji Çözümler',badget:'Kozmetik',badgetColor:'#8e44ad',tags:'#cosmetic,#technology,#application #GürültüEngelleme #GürültüKontrolü',
      url:[
        {name:'Özel Sorun/İhtiyaç/Fırsat Alanı'},
        {name:'Teknoloji Tedarikçisinden Beklentisi'},
        {name:'Aradığı Teknoloji Tedarikçisi Özellikleri'},
        {name:'Teknoloji Tedarikçisi Öncelikli Seçim Kriteri'},
      ]
    },
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 6,
          worker: 6,
          code: "gosterge",
          location: "Ankara",
          sektor: "İnşaat",
          description:
            "İnşaat Malzemeleri AŞ, inşaat sektörüne malzeme tedarik eden bir şirkettir.",
        },
      ],
    },
    {
      id: 3,
      name: "Giyim Dünyası AŞ",
      sektor: 3,
      category: "Tekstil",
      tp: 1,
      ify: 4,
      company: "Giyim Dünyası AŞ",
      nace_kodu: 6,
      tedarikci_tipi: 2,
      gtip: 20,
      yakinlik: 9,
      chart: true,
      group: false,
      users: false,
      pin: true,
      call:{id:3, title:'Tekstil Ürün İthalatı',badget:'Tekstil',badgetColor:'#c0392b',tags:'#tekstile,#product,#ithalat,#GürültüEngelleme #GürültüKontrolü',
      url:[
        {name:'Özel Sorun/İhtiyaç/Fırsat Alanı'},
        {name:'Teknoloji Tedarikçisinden Beklentisi'},
        {name:'Aradığı Teknoloji Tedarikçisi Özellikleri'},
        {name:'Teknoloji Tedarikçisi Öncelikli Seçim Kriteri'},
      ]
      },
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 2,
          worker: 5,
          code: "gosterge",
          location: "Antalya",
          sektor: "Tekstil",
          description:
            "Giyim Dünyası AŞ, kaliteli giyim ürünleri sunarak müşterilerine hizmet vermektedir.",
        },
      ],
    },
    {
      id: 4,
      name: "Teknoloji Harikaları AŞ",
      sektor: 5,
      category: "Teknoloji",
      tp: 6,
      ify: 3,
      company: "Teknoloji Harikaları AŞ",
      nace_kodu: 1,
      tedarikci_tipi: 1,
      gtip: 1,
      yakinlik: 1,
      chart: true,
      group: true,
      users: false,
      pin: true,
      call:{id:4, title:'Yapay Zeka Yüz Tanıma Sistemi',badget:'Tekstil',badgetColor:'#c0392b',tags:'#yapayZeka,#product,#ithalat,#YuzTanima',
      url:[
        {name:'Özel Sorun/İhtiyaç/Fırsat Alanı'},
        {name:'Teknoloji Tedarikçisinden Beklentisi'},
        {name:'Aradığı Teknoloji Tedarikçisi Özellikleri'},
        {name:'Teknoloji Tedarikçisi Öncelikli Seçim Kriteri'},
      ]
      },
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 7,
          worker: 6,
          code: "gosterge",
          location: "İzmir",
          sektor: "Teknoloji",
          description:
            "Teknoloji Harikaları AŞ, teknoloji alanında yenilikçi ürünler sunmaktadır.",
        },
      ],
    },
    {
      id: 5,
      name: "Kozmetik Güzellik Malzemeleri AŞ",
      sektor: 4,
      category: "Kozmetik",
      tp: 5,
      ify: 1,
      company: "Kozmetik Güzellik Malzemeleri AŞ",
      nace_kodu: 7,
      tedarikci_tipi: 3,
      gtip: 12,
      yakinlik: 3,
      chart: true,
      group: false,
      users: false,
      pin: true,
      call:{id:5, title:'Kozmetik Ürünleri Saklama Sistemi',badget:'Tekstil',badgetColor:'#c0392b',tags:'#kozmetik,#product,#ithalat,#ÜrünSaklama #Soğutma',
url:[
  {name:'Özel Sorun/İhtiyaç/Fırsat Alanı'},
  {name:'Teknoloji Tedarikçisinden Beklentisi'},
  {name:'Aradığı Teknoloji Tedarikçisi Özellikleri'},
  {name:'Teknoloji Tedarikçisi Öncelikli Seçim Kriteri'},
]
},
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 3,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Kozmetik",
          description:
            "Kozmetik Güzellik Malzemeleri AŞ, güzellik sektörüne ürünler sunmaktadır.",
        },
      ],
    },
    {
      id: 6,
      name: "Teknoloji Ürünleri Ticaret AŞ",
      sektor: 5,
      category: "Teknoloji",
      tp: 3,
      ify: 4,
      company: "Teknoloji Ürünleri Ticaret AŞ",
      nace_kodu: 5,
      tedarikci_tipi: 1,
      gtip: 6,
      yakinlik: 6,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 2,
          code: "gosterge",
          location: "Antalya",
          sektor: "Teknoloji",
          description:
            "Teknoloji Ürünleri Ticaret AŞ, en yeni teknoloji ürünlerini müşterilerine sunmaktadır.",
        },
      ],
    },
    {
      id: 7,
      name: "Moda İkonları Tekstil",
      sektor: 3,
      category: "Tekstil",
      tp: 2,
      ify: 3,
      company: "Moda İkonları Tekstil",
      nace_kodu: 3,
      tedarikci_tipi: 2,
      gtip: 15,
      yakinlik: 2,
      chart: false,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 1,
          worker: 6,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Moda İkonları Tekstil, modaya yön veren giyim ürünleri sunmaktadır.",
        },
      ],
    },
    {
      id: 8,
      name: "Mobil Teknoloji Çözümleri Ltd.",
      sektor: 5,
      category: "Teknoloji",
      tp: 4,
      ify: 2,
      company: "Mobil Teknoloji Çözümleri Ltd.",
      nace_kodu: 3,
      tedarikci_tipi: 1,
      gtip: 21,
      yakinlik: 4,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 7,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Mobil Teknoloji Çözümleri Ltd., mobil teknoloji alanında çözümler sunmaktadır.",
        },
      ],
    },
    {
      id: 9,
      name: "İnşaat Yapı Malzemeleri AŞ",
      sektor: 2,
      category: "İnşaat",
      tp: 3,
      ify: 1,
      company: "İnşaat Yapı Malzemeleri AŞ",
      nace_kodu: 4,
      tedarikci_tipi: 3,
      gtip: 7,
      yakinlik: 2,
      chart: true,
      group: false,
      users: false,
      pin: true,
      call:{id:6, title:'CNC Makinesi Üretimi',badget:'İnşaat',badgetColor:'#c0392b',tags:'#inşaat,#product,#ithalat,#CNC',
      url:[
        {name:'Özel Sorun/İhtiyaç/Fırsat Alanı'},
        {name:'Teknoloji Tedarikçisinden Beklentisi'},
        {name:'Aradığı Teknoloji Tedarikçisi Özellikleri'},
        {name:'Teknoloji Tedarikçisi Öncelikli Seçim Kriteri'},
      ]
      },
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 4,
          code: "gosterge",
          location: "Ankara",
          sektor: "İnşaat",
          description:
            "İnşaat Yapı Malzemeleri AŞ, inşaat sektörüne malzeme tedarik eden bir şirkettir.",
        },
      ],
    },
    {
      id: 10,
      name: "Spor Giyim Dükkanı",
      sektor: 3,
      category: "Tekstil",
      tp: 2,
      ify: 3,
      company: "Spor Giyim Dükkanı",
      nace_kodu: 3,
      tedarikci_tipi: 2,
      gtip: 14,
      yakinlik: 5,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 5,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Spor Giyim Dükkanı, spor giyim ürünleri sunarak müşterilerine hizmet vermektedir.",
        },
      ],
    },
    {
      id: 11,
      name: "Güzellik Salonu AŞ",
      sektor: 4,
      category: "Kozmetik",
      tp: 1,
      ify: 4,
      company: "Güzellik Salonu AŞ",
      nace_kodu: 7,
      tedarikci_tipi: 2,
      gtip: 13,
      yakinlik: 3,
      chart: true,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 2,
          worker: 6,
          code: "gosterge",
          location: "Antalya",
          sektor: "Kozmetik",
          description:
            "Güzellik Salonu AŞ, güzellik hizmetleri sunarak müşterilerine hizmet vermektedir.",
        },
      ],
    },
    {
      id: 12,
      name: "Tarım Teknolojileri Şirketi",
      sektor: 6,
      category: "Hububat (Tahıl)",
      tp: 4,
      ify: 1,
      company: "Tarım Teknolojileri Şirketi",
      nace_kodu: 6,
      tedarikci_tipi: 1,
      gtip: 10,
      yakinlik: 2,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 5,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Hububat (Tahıl)",
          description:
            "Tarım Teknolojileri Şirketi, tarım sektöründe teknolojik çözümler sunmaktadır.",
        },
      ],
    },
    {
      id: 13,
      name: "Dijital Pazarlama Danışmanlığı AŞ",
      sektor: 5,
      category: "Teknoloji",
      tp: 3,
      ify: 1,
      company: "Dijital Pazarlama Danışmanlığı AŞ",
      nace_kodu: 5,
      tedarikci_tipi: 1,
      gtip: 16,
      yakinlik: 2,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 6,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Dijital Pazarlama Danışmanlığı AŞ, dijital pazarlama stratejileri konusunda danışmanlık hizmeti vermektedir.",
        },
      ],
    },
    {
      id: 14,
      name: "Ev Dekorasyon Mağazası",
      sektor: 3,
      category: "Tekstil",
      tp: 2,
      ify: 3,
      company: "Ev Dekorasyon Mağazası",
      nace_kodu: 2,
      tedarikci_tipi: 3,
      gtip: 11,
      yakinlik: 4,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 8,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Ev Dekorasyon Mağazası, ev dekorasyon ürünleri satan bir mağazadır.",
        },
      ],
    },
    {
      id: 15,
      name: "Kişisel Bakım Ürünleri Şirketi",
      sektor: 4,
      category: "Kozmetik",
      tp: 1,
      ify: 2,
      company: "Kişisel Bakım Ürünleri Şirketi",
      nace_kodu: 6,
      tedarikci_tipi: 2,
      gtip: 13,
      yakinlik: 3,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 2,
          worker: 4,
          code: "gosterge",
          location: "Ankara",
          sektor: "Kozmetik",
          description:
            "Kişisel Bakım Ürünleri Şirketi, kişisel bakım ürünleri üreten bir şirkettir.",
        },
      ],
    },
    {
      id: 16,
      name: "Eğitim Teknolojileri Şirketi",
      sektor: 5,
      category: "Teknoloji",
      tp: 4,
      ify: 1,
      company: "Eğitim Teknolojileri Şirketi",
      nace_kodu: 4,
      tedarikci_tipi: 1,
      gtip: 20,
      yakinlik: 4,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 7,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Eğitim Teknolojileri Şirketi, eğitim alanında teknolojik çözümler sunmaktadır.",
        },
      ],
    },
    {
      id: 17,
      name: "Büro Malzemeleri Satışı Ltd.",
      sektor: 2,
      category: "İnşaat",
      tp: 2,
      ify: 4,
      company: "Büro Malzemeleri Satışı Ltd.",
      nace_kodu: 1,
      tedarikci_tipi: 2,
      gtip: 8,
      yakinlik: 5,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 6,
          code: "gosterge",
          location: "İstanbul",
          sektor: "İnşaat",
          description:
            "Büro Malzemeleri Satışı Ltd., ofis malzemeleri satan bir şirkettir.",
        },
      ],
    },
    {
      id: 18,
      name: "Organik Gıda Üretim Ltd. Şti.",
      sektor: 1,
      category: "Gıda",
      tp: 4,
      ify: 2,
      company: "Organik Gıda Üretim Ltd. Şti.",
      nace_kodu: 3,
      tedarikci_tipi: 1,
      gtip: 5,
      yakinlik: 3,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 30,
          code: "gosterge",
          location: "İzmir",
          sektor: "Gıda",
          description:
            "Organik Gıda Üretim Ltd. Şti., organik gıda üreten bir şirkettir ve sağlıklı beslenmeyi teşvik etmektedir.",
        },
      ],
    },
    {
      id: 19,
      name: "Yapı Malzemeleri İmalatı AŞ",
      sektor: 2,
      category: "İnşaat",
      tp: 5,
      ify: 1,
      company: "Yapı Malzemeleri İmalatı AŞ",
      nace_kodu: 2,
      tedarikci_tipi: 1,
      gtip: 10,
      yakinlik: 2,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 6,
          worker: 85,
          code: "gosterge",
          location: "Ankara",
          sektor: "İnşaat",
          description:
            "Yapı Malzemeleri İmalatı AŞ, inşaat sektörüne malzemeler üreten bir şirkettir.",
        },
      ],
    },
    {
      id: 20,
      name: "Tekstil Ürünleri Toptancılığı",
      sektor: 3,
      category: "Tekstil",
      tp: 4,
      ify: 3,
      company: "Tekstil Ürünleri Toptancılığı",
      nace_kodu: 5,
      tedarikci_tipi: 2,
      gtip: 13,
      yakinlik: 5,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 50,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Tekstil Ürünleri Toptancılığı, tekstil ürünleri toptan satan bir şirkettir.",
        },
      ],
    },
    {
      id: 21,
      name: "Kozmetik Ürünleri İthalatı",
      sektor: 4,
      category: "Kozmetik",
      tp: 3,
      ify: 4,
      company: "Kozmetik Ürünleri İthalatı",
      nace_kodu: 1,
      tedarikci_tipi: 3,
      gtip: 4,
      yakinlik: 4,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 25,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Kozmetik",
          description:
            "Kozmetik Ürünleri İthalatı, kozmetik ürünleri ithal eden bir şirkettir ve güzellik endüstrisine katkı sağlamaktadır.",
        },
      ],
    },
    {
      id: 22,
      name: "Yazılım Geliştirme Ajansı",
      sektor: 5,
      category: "Teknoloji",
      tp: 2,
      ify: 1,
      company: "Yazılım Geliştirme Ajansı",
      nace_kodu: 6,
      tedarikci_tipi: 2,
      gtip: 18,
      yakinlik: 3,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 20,
          code: "gosterge",
          location: "Ankara",
          sektor: "Teknoloji",
          description:
            "Yazılım Geliştirme Ajansı, yazılım çözümleri üreten bir şirkettir ve teknolojiye katkıda bulunmaktadır.",
        },
      ],
    },
    {
      id: 23,
      name: "Tarım Ekipmanları Satışı",
      sektor: 1,
      category: "Gıda",
      tp: 1,
      ify: 2,
      company: "Tarım Ekipmanları Satışı",
      nace_kodu: 5,
      tedarikci_tipi: 1,
      gtip: 9,
      yakinlik: 2,
      chart: false,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 2,
          worker: 10,
          code: "gosterge",
          location: "İzmir",
          sektor: "Gıda",
          description:
            "Tarım Ekipmanları Satışı, tarım sektörüne ekipmanlar satan bir şirkettir ve tarımı desteklemektedir.",
        },
      ],
    },
    {
      id: 24,
      name: "Mimari Tasarım Stüdyosu",
      sektor: 2,
      category: "İnşaat",
      tp: 2,
      ify: 4,
      company: "Mimari Tasarım Stüdyosu",
      nace_kodu: 4,
      tedarikci_tipi: 3,
      gtip: 15,
      yakinlik: 4,
      chart: false,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 15,
          code: "gosterge",
          location: "İstanbul",
          sektor: "İnşaat",
          description:
            "Mimari Tasarım Stüdyosu, mimari tasarım hizmetleri sunan bir stüdyodur ve inşaat projelerine katkı sağlamaktadır.",
        },
      ],
    },
    {
      id: 25,
      name: "Eğitim Malzemeleri İmalatı",
      sektor: 5,
      category: "Teknoloji",
      tp: 3,
      ify: 1,
      company: "Eğitim Malzemeleri İmalatı",
      nace_kodu: 3,
      tedarikci_tipi: 1,
      gtip: 19,
      yakinlik: 5,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 12,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Eğitim Malzemeleri İmalatı, eğitim sektörüne malzemeler üreten bir şirkettir ve eğitimde kaliteyi artırmaktadır.",
        },
      ],
    },
    {
      id: 26,
      name: "Güzellik ve Spa Merkezi",
      sektor: 4,
      category: "Kozmetik",
      tp: 2,
      ify: 3,
      company: "Güzellik ve Spa Merkezi",
      nace_kodu: 1,
      tedarikci_tipi: 2,
      gtip: 12,
      yakinlik: 4,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 18,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Kozmetik",
          description:
            "Güzellik ve Spa Merkezi, güzellik ve spa hizmetleri sunan bir merkezdir ve müşterilerine lüks bir deneyim sunmaktadır.",
        },
      ],
    },
    {
      id: 27,
      name: "Yapay Zeka Çözümleri AŞ",
      sektor: 5,
      category: "Teknoloji",
      tp: 4,
      ify: 1,
      company: "Yapay Zeka Çözümleri AŞ",
      nace_kodu: 6,
      tedarikci_tipi: 1,
      gtip: 21,
      yakinlik: 3,
      chart: false,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 22,
          code: "gosterge",
          location: "Ankara",
          sektor: "Teknoloji",
          description:
            "Yapay Zeka Çözümleri AŞ, yapay zeka teknolojileri geliştiren bir şirkettir ve geleceğin teknolojilerine yön vermektedir.",
        },
      ],
    },
    {
      id: 28,
      name: "Sürdürülebilir Enerji Şirketi",
      sektor: 5,
      category: "Enerji",
      tp: 5,
      ify: 3,
      company: "Sürdürülebilir Enerji Şirketi",
      nace_kodu: 7,
      tedarikci_tipi: 1,
      gtip: 23,
      yakinlik: 4,
      chart: true,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 6,
          worker: 60,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Enerji",
          description:
            "Sürdürülebilir Enerji Şirketi, temiz enerji üreten bir şirkettir ve çevreye duyarlı enerji çözümleri sunmaktadır.",
        },
      ],
    },
    {
      id: 29,
      name: "Otomotiv Parça Üreticisi Ltd. Şti.",
      sektor: 2,
      category: "Otomotiv",
      tp: 4,
      ify: 2,
      company: "Otomotiv Parça Üreticisi Ltd. Şti.",
      nace_kodu: 8,
      tedarikci_tipi: 2,
      gtip: 17,
      yakinlik: 2,
      chart: false,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 45,
          code: "gosterge",
          location: "Bursa",
          sektor: "Otomotiv",
          description:
            "Otomotiv Parça Üreticisi Ltd. Şti., otomotiv sektörü için parça üreten bir şirkettir ve kaliteli ürünler sunmaktadır.",
        },
      ],
    },
    {
      id: 30,
      name: "Moda Tasarım Atölyesi",
      sektor: 3,
      category: "Tekstil",
      tp: 3,
      ify: 1,
      company: "Moda Tasarım Atölyesi",
      nace_kodu: 9,
      tedarikci_tipi: 1,
      gtip: 11,
      yakinlik: 5,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 28,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Moda Tasarım Atölyesi, moda dünyasına yaratıcı tasarımlar sunan bir atölyedir ve stil sahibi giyim ürünleri üretmektedir.",
        },
      ],
    },
    {
      id: 31,
      name: "Sağlık Danışmanlık Hizmetleri",
      sektor: 6,
      category: "Sağlık",
      tp: 2,
      ify: 2,
      company: "Sağlık Danışmanlık Hizmetleri",
      nace_kodu: 10,
      tedarikci_tipi: 3,
      gtip: 14,
      yakinlik: 3,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 22,
          code: "gosterge",
          location: "Ankara",
          sektor: "Sağlık",
          description:
            "Sağlık Danışmanlık Hizmetleri, sağlık alanında danışmanlık hizmetleri sunan bir şirkettir ve sağlığı teşvik etmektedir.",
        },
      ],
    },
    {
      id: 32,
      name: "Eğlence ve Etkinlik Yönetimi",
      sektor: 7,
      category: "Eğlence",
      tp: 3,
      ify: 4,
      company: "Eğlence ve Etkinlik Yönetimi",
      nace_kodu: 11,
      tedarikci_tipi: 2,
      gtip: 20,
      yakinlik: 4,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 35,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Eğlence",
          description:
            "Eğlence ve Etkinlik Yönetimi, eğlence sektöründe etkinlikler düzenleyen bir şirkettir ve unutulmaz anlar yaratmaktadır.",
        },
      ],
    },
    {
      id: 33,
      name: "Oyuncak Üreticisi",
      sektor: 8,
      category: "Oyuncak",
      tp: 2,
      ify: 3,
      company: "Oyuncak Üreticisi",
      nace_kodu: 12,
      tedarikci_tipi: 1,
      gtip: 9,
      yakinlik: 2,
      chart: false,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 15,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Oyuncak",
          description:
            "Oyuncak Üreticisi, çocuklar için eğitici ve eğlenceli oyuncaklar üreten bir şirkettir ve çocukların gelişimine katkı sağlamaktadır.",
        },
      ],
    },
    {
      id: 34,
      name: "Bilgisayar Donanım Satışı",
      sektor: 5,
      category: "Teknoloji",
      tp: 3,
      ify: 2,
      company: "Bilgisayar Donanım Satışı",
      nace_kodu: 13,
      tedarikci_tipi: 1,
      gtip: 8,
      yakinlik: 3,
      chart: false,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 20,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Bilgisayar Donanım Satışı, yüksek kaliteli bilgisayar donanımı sunan bir şirkettir ve teknolojiye katkı sağlamaktadır.",
        },
      ],
    },
    {
      id: 35,
      name: "Organik Tarım Ürünleri Çiftliği",
      sektor: 1,
      category: "Gıda",
      tp: 6,
      ify: 1,
      company: "Organik Tarım Ürünleri Çiftliği",
      nace_kodu: 14,
      tedarikci_tipi: 1,
      gtip: 1,
      yakinlik: 5,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 6,
          worker: 55,
          code: "gosterge",
          location: "Ankara",
          sektor: "Gıda",
          description:
            "Organik Tarım Ürünleri Çiftliği, sağlıklı ve organik tarım ürünleri üreten bir çiftliktir ve doğal lezzetler sunmaktadır.",
        },
      ],
    },
    {
      id: 36,
      name: "Küresel Lojistik Şirketi",
      sektor: 9,
      category: "Lojistik",
      tp: 5,
      ify: 4,
      company: "Küresel Lojistik Şirketi",
      nace_kodu: 15,
      tedarikci_tipi: 1,
      gtip: 7,
      yakinlik: 4,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 48,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Lojistik",
          description:
            "Küresel Lojistik Şirketi, uluslararası taşımacılıkta hızlı ve güvenilir hizmetler sunan bir şirkettir ve ticaretin büyümesine katkı sağlamaktadır.",
        },
      ],
    },
    {
      id: 37,
      name: "Mücevher Tasarım Atölyesi",
      sektor: 10,
      category: "Takı",
      tp: 2,
      ify: 1,
      company: "Mücevher Tasarım Atölyesi",
      nace_kodu: 16,
      tedarikci_tipi: 2,
      gtip: 5,
      yakinlik: 5,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 12,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Takı",
          description:
            "Mücevher Tasarım Atölyesi, özel tasarım mücevherler üreten bir atölyedir ve zarafeti yaratmaktadır.",
        },
      ],
    },
    {
      id: 38,
      name: "Yazılım Geliştirme Firması",
      sektor: 5,
      category: "Teknoloji",
      tp: 4,
      ify: 1,
      company: "Yazılım Geliştirme Firması",
      nace_kodu: 17,
      tedarikci_tipi: 1,
      gtip: 8,
      yakinlik: 2,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 30,
          code: "gosterge",
          location: "Ankara",
          sektor: "Teknoloji",
          description:
            "Yazılım Geliştirme Firması, özelleştirilmiş yazılım çözümleri sunan bir firmadır ve teknolojik yeniliklerle iş dünyasına katkı sağlar.",
        },
      ],
    },
    {
      id: 39,
      name: "Organik Kozmetik Üreticisi",
      sektor: 4,
      category: "Kozmetik",
      tp: 3,
      ify: 1,
      company: "Organik Kozmetik Üreticisi",
      nace_kodu: 18,
      tedarikci_tipi: 1,
      gtip: 10,
      yakinlik: 4,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 25,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Kozmetik",
          description:
            "Organik Kozmetik Üreticisi, doğal ve organik kozmetik ürünleri üreten bir şirkettir ve güzellik ve bakımı teşvik eder.",
        },
      ],
    },
    {
      id: 40,
      name: "İnşaat Malzemeleri Tedarikçisi",
      sektor: 2,
      category: "İnşaat",
      tp: 4,
      ify: 3,
      company: "İnşaat Malzemeleri Tedarikçisi",
      nace_kodu: 19,
      tedarikci_tipi: 1,
      gtip: 12,
      yakinlik: 3,
      chart: false,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 40,
          code: "gosterge",
          location: "İzmir",
          sektor: "İnşaat",
          description:
            "İnşaat Malzemeleri Tedarikçisi, inşaat sektörü için malzeme tedarik eden bir şirkettir ve projelerin başarılı bir şekilde tamamlanmasına yardımcı olur.",
        },
      ],
    },
    {
      id: 41,
      name: "Eğitim Danışmanlık Şirketi",
      sektor: 11,
      category: "Eğitim",
      tp: 2,
      ify: 2,
      company: "Eğitim Danışmanlık Şirketi",
      nace_kodu: 20,
      tedarikci_tipi: 4,
      gtip: 14,
      yakinlik: 4,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 18,
          code: "gosterge",
          location: "Ankara",
          sektor: "Eğitim",
          description:
            "Eğitim Danışmanlık Şirketi, eğitim alanında danışmanlık hizmetleri sunan bir şirkettir ve öğrencilerin geleceğini şekillendirmeye yardımcı olur.",
        },
      ],
    },
    {
      id: 42,
      name: "Organik Tarım Ürünleri İhracatçısı",
      sektor: 1,
      category: "Gıda",
      tp: 6,
      ify: 5,
      company: "Organik Tarım Ürünleri İhracatçısı",
      nace_kodu: 21,
      tedarikci_tipi: 1,
      gtip: 2,
      yakinlik: 9,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 7,
          worker: 70,
          code: "gosterge",
          location: "İzmir",
          sektor: "Gıda",
          description:
            "Organik Tarım Ürünleri İhracatçısı, dünya genelinde organik gıda ürünleri ihraç eden bir şirkettir ve sağlıklı beslenmeyi teşvik eder.",
        },
      ],
    },
    {
      id: 43,
      name: "Teknoloji Danışmanlık Şirketi",
      sektor: 5,
      category: "Teknoloji",
      tp: 4,
      ify: 2,
      company: "Teknoloji Danışmanlık Şirketi",
      nace_kodu: 17,
      tedarikci_tipi: 2,
      gtip: 8,
      yakinlik: 2,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 28,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Teknoloji Danışmanlık Şirketi, işletmelere teknoloji alanında danışmanlık hizmetleri sunan bir firmadır ve dijital dönüşümü destekler.",
        },
      ],
    },
    {
      id: 44,
      name: "Müzik Stüdyosu",
      sektor: 12,
      category: "Eğlence",
      tp: 2,
      ify: 3,
      company: "Müzik Stüdyosu",
      nace_kodu: 22,
      tedarikci_tipi: 4,
      gtip: 15,
      yakinlik: 2,
      chart: false,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 2,
          worker: 10,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Eğlence",
          description:
            "Müzik Stüdyosu, sanatçılara kayıt ve prodüksiyon hizmetleri sunan bir stüdyodur ve müziğin gücünü vurgular.",
        },
      ],
    },
    {
      id: 45,
      name: "Giyim Üreticisi",
      sektor: 3,
      category: "Tekstil",
      tp: 4,
      ify: 1,
      company: "Giyim Üreticisi",
      nace_kodu: 23,
      tedarikci_tipi: 1,
      gtip: 3,
      yakinlik: 5,
      chart: true,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 35,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Giyim Üreticisi, moda ve tekstil ürünleri üreten bir firmadır ve tarzı vurgular.",
        },
      ],
    },
    {
      id: 46,
      name: "Otomotiv Parça Üreticisi",
      sektor: 6,
      category: "Otomotiv",
      tp: 5,
      ify: 4,
      company: "Otomotiv Parça Üreticisi",
      nace_kodu: 24,
      tedarikci_tipi: 1,
      gtip: 11,
      yakinlik: 3,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 45,
          code: "gosterge",
          location: "İzmir",
          sektor: "Otomotiv",
          description:
            "Otomotiv Parça Üreticisi, yüksek kaliteli otomotiv parçaları üreten bir şirkettir ve sürüşü güvenli kılar.",
        },
      ],
    },
    {
      id: 47,
      name: "Film Prodüksiyon Şirketi",
      sektor: 12,
      category: "Eğlence",
      tp: 3,
      ify: 2,
      company: "Film Prodüksiyon Şirketi",
      nace_kodu: 25,
      tedarikci_tipi: 4,
      gtip: 16,
      yakinlik: 2,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 22,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Eğlence",
          description:
            "Film Prodüksiyon Şirketi, sinema ve dizi prodüksiyon hizmetleri sunan bir firmadır ve hikayeleri hayata geçirir.",
        },
      ],
    },
    {
      id: 48,
      name: "Ambalaj Malzemesi Üreticisi",
      sektor: 7,
      category: "Ambalaj",
      tp: 4,
      ify: 1,
      company: "Ambalaj Malzemesi Üreticisi",
      nace_kodu: 26,
      tedarikci_tipi: 1,
      gtip: 6,
      yakinlik: 4,
      chart: false,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 28,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Ambalaj",
          description:
            "Ambalaj Malzemesi Üreticisi, yaratıcı ambalaj çözümleri sunan bir şirkettir ve ürünleri öne çıkarır.",
        },
      ],
    },
    {
      id: 49,
      name: "Otel ve Tatil Köyü",
      sektor: 9,
      category: "Turizm",
      tp: 5,
      ify: 4,
      company: "Otel ve Tatil Köyü",
      nace_kodu: 27,
      tedarikci_tipi: 1,
      gtip: 17,
      yakinlik: 5,
      chart: true,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 7,
          worker: 120,
          code: "gosterge",
          location: "Antalya",
          sektor: "Turizm",
          description:
            "Otel ve Tatil Köyü, muhteşem tatil deneyimleri sunan bir tesisdir ve konuklarına unutulmaz anılar yaşatır.",
        },
      ],
    },
    {
      id: 50,
      name: "Organik Tarım Ürünleri Mağazası",
      sektor: 1,
      category: "Gıda",
      tp: 2,
      ify: 1,
      company: "Organik Tarım Ürünleri Mağazası",
      nace_kodu: 28,
      tedarikci_tipi: 1,
      gtip: 2,
      yakinlik: 1,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 12,
          code: "gosterge",
          location: "Ankara",
          sektor: "Gıda",
          description:
            "Organik Tarım Ürünleri Mağazası, sağlıklı gıda ürünleri sunan bir mağazadır ve doğal yaşamı teşvik eder.",
        },
      ],
    },
    {
      id: 51,
      name: "Yapı ve İnşaat Mühendisliği Şirketi",
      sektor: 2,
      category: "İnşaat",
      tp: 5,
      ify: 2,
      company: "Yapı ve İnşaat Mühendisliği Şirketi",
      nace_kodu: 29,
      tedarikci_tipi: 1,
      gtip: 12,
      yakinlik: 3,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 6,
          worker: 55,
          code: "gosterge",
          location: "İstanbul",
          sektor: "İnşaat",
          description:
            "Yapı ve İnşaat Mühendisliği Şirketi, mühendislik hizmetleri sunan bir firmadır ve projelerin başarılı bir şekilde tamamlanmasına yardımcı olur.",
        },
      ],
    },
    {
      id: 52,
      name: "E-ticaret Teknolojileri Şirketi",
      sektor: 5,
      category: "Teknoloji",
      tp: 3,
      ify: 2,
      company: "E-ticaret Teknolojileri Şirketi",
      nace_kodu: 17,
      tedarikci_tipi: 1,
      gtip: 8,
      yakinlik: 2,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 35,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "E-ticaret Teknolojileri Şirketi, çevrimiçi ticaret için teknoloji çözümleri sunan bir firmadır ve işletmelerin çevrimiçi varlığını artırır.",
        },
      ],
    },
    {
      id: 53,
      name: "Kültürel Etkinlik Yönetimi Şirketi",
      sektor: 12,
      category: "Eğlence",
      tp: 2,
      ify: 2,
      company: "Kültürel Etkinlik Yönetimi Şirketi",
      nace_kodu: 30,
      tedarikci_tipi: 4,
      gtip: 16,
      yakinlik: 3,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 20,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Eğlence",
          description:
            "Kültürel Etkinlik Yönetimi Şirketi, kültürel etkinliklerin organizasyonunu üstlenen bir firmadır ve sanatı topluma taşır.",
        },
      ],
    },
    {
      id: 54,
      name: "Otomotiv Yedek Parça Mağazası",
      sektor: 6,
      category: "Otomotiv",
      tp: 2,
      ify: 1,
      company: "Otomotiv Yedek Parça Mağazası",
      nace_kodu: 31,
      tedarikci_tipi: 1,
      gtip: 11,
      yakinlik: 1,
      chart: false,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 2,
          worker: 8,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Otomotiv",
          description:
            "Otomotiv Yedek Parça Mağazası, kaliteli yedek parçalar sunan bir mağazadır ve araçların bakımını kolaylaştırır.",
        },
      ],
    },
    {
      id: 55,
      name: "Kozmetik Ürünler Üreticisi",
      sektor: 4,
      category: "Kozmetik",
      tp: 4,
      ify: 1,
      company: "Kozmetik Ürünler Üreticisi",
      nace_kodu: 32,
      tedarikci_tipi: 1,
      gtip: 5,
      yakinlik: 2,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 30,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Kozmetik",
          description:
            "Kozmetik Ürünler Üreticisi, güzellik ve kişisel bakım ürünleri üreten bir firmadır ve güzelliği vurgular.",
        },
      ],
    },
    {
      id: 56,
      name: "Bilgisayar Yazılım Şirketi",
      sektor: 5,
      category: "Teknoloji",
      tp: 3,
      ify: 2,
      company: "Bilgisayar Yazılım Şirketi",
      nace_kodu: 18,
      tedarikci_tipi: 1,
      gtip: 8,
      yakinlik: 3,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 40,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Teknoloji",
          description:
            "Bilgisayar Yazılım Şirketi, özelleştirilmiş yazılım çözümleri sunan bir firmadır ve işletmelerin dijital dönüşümünü destekler.",
        },
      ],
    },
    {
      id: 57,
      name: "Ev Dekorasyon Mağazası",
      sektor: 11,
      category: "Perakende",
      tp: 2,
      ify: 1,
      company: "Ev Dekorasyon Mağazası",
      nace_kodu: 33,
      tedarikci_tipi: 1,
      gtip: 7,
      yakinlik: 1,
      chart: false,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 15,
          code: "gosterge",
          location: "İzmir",
          sektor: "Perakende",
          description:
            "Ev Dekorasyon Mağazası, şık ev dekorasyon ürünleri sunan bir mağazadır ve yaşam alanlarını güzelleştirir.",
        },
      ],
    },
    {
      id: 58,
      name: "Yatırım Danışmanlık Şirketi",
      sektor: 8,
      category: "Finans",
      tp: 3,
      ify: 4,
      company: "Yatırım Danışmanlık Şirketi",
      nace_kodu: 34,
      tedarikci_tipi: 2,
      gtip: 18,
      yakinlik: 4,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 5,
          worker: 25,
          code: "gosterge",
          location: "Ankara",
          sektor: "Finans",
          description:
            "Yatırım Danışmanlık Şirketi, yatırım danışmanlığı hizmetleri sunan bir firmadır ve mali başarıyı teşvik eder.",
        },
      ],
    },
    {
      id: 59,
      name: "Organik Tarım Çiftliği",
      sektor: 1,
      category: "Gıda",
      tp: 4,
      ify: 5,
      company: "Organik Tarım Çiftliği",
      nace_kodu: 35,
      tedarikci_tipi: 1,
      gtip: 1,
      yakinlik: 2,
      chart: false,
      group: false,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 6,
          worker: 18,
          code: "gosterge",
          location: "İzmir",
          sektor: "Gıda",
          description:
            "Organik Tarım Çiftliği, sağlıklı ve organik ürünler üreten bir çiftliktir ve doğal beslenmeyi teşvik eder.",
        },
      ],
    },
    {
      id: 60,
      name: "Elektronik Ürünler Mağazası",
      sektor: 5,
      category: "Perakende",
      tp: 3,
      ify: 2,
      company: "Elektronik Ürünler Mağazası",
      nace_kodu: 36,
      tedarikci_tipi: 1,
      gtip: 9,
      yakinlik: 1,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 20,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Perakende",
          description:
            "Elektronik Ürünler Mağazası, son teknoloji elektronik ürünler sunan bir mağazadır ve teknoloji tutkunlarını memnun eder.",
        },
      ],
    },
    {
      id: 61,
      name: "Mücevherat Atölyesi",
      sektor: 10,
      category: "Perakende",
      tp: 2,
      ify: 1,
      company: "Mücevherat Atölyesi",
      nace_kodu: 37,
      tedarikci_tipi: 1,
      gtip: 10,
      yakinlik: 1,
      chart: false,
      group: false,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 3,
          worker: 8,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Perakende",
          description:
            "Mücevherat Atölyesi, özel tasarım mücevherler üreten bir atölyedir ve zarafeti vurgular.",
        },
      ],
    },
    {
      id: 62,
      name: "Enerji Üretim Şirketi",
      sektor: 7,
      category: "Enerji",
      tp: 5,
      ify: 3,
      company: "Enerji Üretim Şirketi",
      nace_kodu: 38,
      tedarikci_tipi: 1,
      gtip: 14,
      yakinlik: 3,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 7,
          worker: 60,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Enerji",
          description:
            "Enerji Üretim Şirketi, sürdürülebilir enerji üreten bir şirkettir ve çevreyi koruma misyonunu taşır.",
        },
      ],
    },
    {
      id: 63,
      name: "Moda Tasarım Stüdyosu",
      sektor: 3,
      category: "Tekstil",
      tp: 3,
      ify: 2,
      company: "Moda Tasarım Stüdyosu",
      nace_kodu: 39,
      tedarikci_tipi: 1,
      gtip: 4,
      yakinlik: 2,
      chart: true,
      group: false,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: "Hakkımızda",
          ciro: 4,
          worker: 15,
          code: "gosterge",
          location: "İstanbul",
          sektor: "Tekstil",
          description:
            "Moda Tasarım Stüdyosu, benzersiz moda tasarımları yapan bir stüdyodur ve stil sahibi müşterileri memnun eder.",
        },
      ],
    },
    {
    id: 64,
    name: 'Ev Eşyaları Toptancısı',
    sektor: 11,
    category: 'Perakende',
    tp: 4,
    ify: 1,
    company: 'Ev Eşyaları Toptancısı',
    nace_kodu: 40,
    tedarikci_tipi: 1,
    gtip: 7,
    yakinlik: 2,
    chart: true,
    group: true,
    users: true,
    pin: false,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 6,
        worker: 25,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Perakende',
        description: 'Ev Eşyaları Toptancısı, uygun fiyatlı ev eşyaları sunan bir toptancıdır ve evleri güzelleştirir.',
      },
    ],
  },
  {
    id: 65,
    name: 'Gıda Üretim Fabrikası',
    sektor: 1,
    category: 'Gıda',
    tp: 5,
    ify: 4,
    company: 'Gıda Üretim Fabrikası',
    nace_kodu: 41,
    tedarikci_tipi: 1,
    gtip: 1,
    yakinlik: 3,
    chart: true,
    group: false,
    users: false,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 8,
        worker: 75,
        code: 'gosterge',
        location: 'Ankara',
        sektor: 'Gıda',
        description: 'Gıda Üretim Fabrikası, lezzetli gıda ürünleri üreten bir fabrikadır ve beslenmeyi iyileştirir.',
      },
    ],
  },
  {
    id: 66,
    name: 'Müzik Prodüksiyon Şirketi',
    sektor: 9,
    category: 'Eğlence',
    tp: 2,
    ify: 2,
    company: 'Müzik Prodüksiyon Şirketi',
    nace_kodu: 42,
    tedarikci_tipi: 1,
    gtip: 20,
    yakinlik: 1,
    chart: false,
    group: false,
    users: true,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 4,
        worker: 10,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Eğlence',
        description: 'Müzik Prodüksiyon Şirketi, müzik prodüksiyon hizmetleri sunan bir şirkettir ve sanatçıları destekler.',
      },
    ],
  },
  {
    id: 67,
    name: 'Yapı Malzemeleri Üreticisi',
    sektor: 2,
    category: 'İnşaat',
    tp: 5,
    ify: 1,
    company: 'Yapı Malzemeleri Üreticisi',
    nace_kodu: 43,
    tedarikci_tipi: 1,
    gtip: 2,
    yakinlik: 2,
    chart: true,
    group: true,
    users: false,
    pin: false,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 7,
        worker: 50,
        code: 'gosterge',
        location: 'İzmir',
        sektor: 'İnşaat',
        description: 'Yapı Malzemeleri Üreticisi, yüksek kaliteli yapı malzemeleri üreten bir şirkettir ve inşaat projelerini destekler.',
      },
    ],
  },
  {
    id: 68,
    name: 'Sağlık ve Wellness Merkezi',
    sektor: 6,
    category: 'Sağlık',
    tp: 3,
    ify: 3,
    company: 'Sağlık ve Wellness Merkezi',
    nace_kodu: 44,
    tedarikci_tipi: 1,
    gtip: 17,
    yakinlik: 1,
    chart: true,
    group: false,
    users: true,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 5,
        worker: 15,
        code: 'gosterge',
        location: 'Ankara',
        sektor: 'Sağlık',
        description: 'Sağlık ve Wellness Merkezi, sağlık hizmetleri sunan bir merkezdir ve insanların sağlıklı yaşam biçimlerini teşvik eder.',
      },
    ],
  },
  {
    id: 69,
    name: 'Eğitim Danışmanlık Şirketi',
    sektor: 12,
    category: 'Eğitim',
    tp: 2,
    ify: 2,
    company: 'Eğitim Danışmanlık Şirketi',
    nace_kodu: 45,
    tedarikci_tipi: 1,
    gtip: 16,
    yakinlik: 3,
    chart: true,
    group: true,
    users: false,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 4,
        worker: 12,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Eğitim',
        description: 'Eğitim Danışmanlık Şirketi, eğitim danışmanlığı hizmetleri sunan bir firmadır ve öğrencilerin başarısını artırır.',
      },
    ],
  },
  {
    id: 70,
    name: 'Oyun Geliştirme Stüdyosu',
    sektor: 5,
    category: 'Teknoloji',
    tp: 3,
    ify: 2,
    company: 'Oyun Geliştirme Stüdyosu',
    nace_kodu: 46,
    tedarikci_tipi: 1,
    gtip: 8,
    yakinlik: 1,
    chart: true,
    group: false,
    users: true,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 5,
        worker: 30,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Teknoloji',
        description: 'Oyun Geliştirme Stüdyosu, eğlenceli ve yaratıcı oyunlar geliştiren bir stüdyodur ve oyunseverleri memnun eder.',
      },
    ],
  },
  {
    id: 71,
    name: 'Evcil Hayvan Mağazası',
    sektor: 13,
    category: 'Perakende',
    tp: 2,
    ify: 4,
    company: 'Evcil Hayvan Mağazası',
    nace_kodu: 47,
    tedarikci_tipi: 1,
    gtip: 15,
    yakinlik: 2,
    chart: true,
    group: true,
    users: false,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 4,
        worker: 10,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Perakende',
        description: 'Evcil Hayvan Mağazası, evcil hayvan sahiplerine yönelik ürünler sunan bir mağazadır ve evcil hayvanları mutlu eder.',
      },
    ],
  },
  {
    id: 72,
    name: 'Otomotiv Parça Üreticisi',
    sektor: 8,
    category: 'Otomotiv',
    tp: 5,
    ify: 2,
    company: 'Otomotiv Parça Üreticisi',
    nace_kodu: 48,
    tedarikci_tipi: 1,
    gtip: 11,
    yakinlik: 3,
    chart: true,
    group: true,
    users: true,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 7,
        worker: 60,
        code: 'gosterge',
        location: 'Bursa',
        sektor: 'Otomotiv',
        description: 'Otomotiv Parça Üreticisi, yüksek kaliteli otomotiv parçaları üreten bir firmadır ve otomotiv endüstrisine katkı sağlar.',
      },
    ],
  },
  {
    id: 73,
    name: 'Kozmetik Ürünler Mağazası',
    sektor: 4,
    category: 'Perakende',
    tp: 3,
    ify: 3,
    company: 'Kozmetik Ürünler Mağazası',
    nace_kodu: 49,
    tedarikci_tipi: 1,
    gtip: 6,
    yakinlik: 2,
    chart: true,
    group: false,
    users: false,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 5,
        worker: 20,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Perakende',
        description: 'Kozmetik Ürünler Mağazası, güzellik ürünleri sunan bir mağazadır ve müşterilerin güzelliklerini destekler.',
      },
    ],
  },
  {
    id: 74,
    name: 'Yazılım Geliştirme Şirketi',
    sektor: 5,
    category: 'Teknoloji',
    tp: 4,
    ify: 1,
    company: 'Yazılım Geliştirme Şirketi',
    nace_kodu: 50,
    tedarikci_tipi: 1,
    gtip: 19,
    yakinlik: 2,
    chart: true,
    group: true,
    users: false,
    pin: false,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 6,
        worker: 40,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Teknoloji',
        description: 'Yazılım Geliştirme Şirketi, özelleştirilmiş yazılım çözümleri sunan bir şirkettir ve işletmelerin verimliliğini artırır.',
      },
    ],
  },
  {
    id: 75,
    name: 'Organik Tarım İşletmesi',
    sektor: 11,
    category: 'Tarım',
    tp: 4,
    ify: 3,
    company: 'Organik Tarım İşletmesi',
    nace_kodu: 51,
    tedarikci_tipi: 1,
    gtip: 5,
    yakinlik: 3,
    chart: true,
    group: true,
    users: true,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 7,
        worker: 30,
        code: 'gosterge',
        location: 'Mersin',
        sektor: 'Tarım',
        description: 'Organik Tarım İşletmesi, organik tarım ürünleri yetiştiren bir işletmedir ve sağlıklı beslenmeyi teşvik eder.',
      },
    ],
  },
  {
    id: 76,
    name: 'Güvenlik Hizmetleri Şirketi',
    sektor: 10,
    category: 'Güvenlik',
    tp: 3,
    ify: 2,
    company: 'Güvenlik Hizmetleri Şirketi',
    nace_kodu: 52,
    tedarikci_tipi: 1,
    gtip: 21,
    yakinlik: 2,
    chart: true,
    group: true,
    users: false,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 5,
        worker: 20,
        code: 'gosterge',
        location: 'Ankara',
        sektor: 'Güvenlik',
        description: 'Güvenlik Hizmetleri Şirketi, güvenlik hizmetleri sunan bir şirkettir ve kurumların güvenliğini sağlar.',
      },
    ],
  },
  {
    id: 77,
    name: 'Tekstil Tasarım Atölyesi',
    sektor: 3,
    category: 'Tekstil',
    tp: 2,
    ify: 2,
    company: 'Tekstil Tasarım Atölyesi',
    nace_kodu: 53,
    tedarikci_tipi: 1,
    gtip: 4,
    yakinlik: 1,
    chart: false,
    group: false,
    users: true,
    pin: false,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 4,
        worker: 10,
        code: 'gosterge',
        location: 'İzmir',
        sektor: 'Tekstil',
        description: 'Tekstil Tasarım Atölyesi, özgün tekstil tasarımları sunan bir atölyedir ve giyim sektörüne katkı sağlar.',
      },
    ],
  },
  {
    id: 78,
    name: 'Mobilya Mağazası',
    sektor: 11,
    category: 'Perakende',
    tp: 3,
    ify: 3,
    company: 'Mobilya Mağazası',
    nace_kodu: 54,
    tedarikci_tipi: 1,
    gtip: 7,
    yakinlik: 3,
    chart: true,
    group: false,
    users: false,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 5,
        worker: 20,
        code: 'gosterge',
        location: 'İstanbul',
        sektor: 'Perakende',
        description: 'Mobilya Mağazası, şık mobilya ürünleri sunan bir mağazadır ve evleri güzelleştirir.',
      },
    ],
  },
  {
    id: 79,
    name: 'Temizlik Hizmetleri Şirketi',
    sektor: 10,
    category: 'Temizlik',
    tp: 4,
    ify: 2,
    company: 'Temizlik Hizmetleri Şirketi',
    nace_kodu: 55,
    tedarikci_tipi: 1,
    gtip: 14,
    yakinlik: 2,
    chart: true,
    group: true,
    users: true,
    pin: true,
    companyInfo: [
      {
        name: 'Hakkımızda',
        ciro: 6,
        worker: 25,
        code: 'gosterge',
        location: 'Ankara',
        sektor: 'Temizlik',
        description: 'Temizlik Hizmetleri Şirketi, profesyonel temizlik hizmetleri sunan bir şirkettir ve temiz bir çevre sağlar.',
      },
    ],
  },
    {
      id: 80,
      name: 'Bilgisayar Teknolojileri Danışmanlığı',
      sektor: 5,
      category: 'Teknoloji',
      tp: 4,
      ify: 1,
      company: 'Tekno Danışmanlar',
      nace_kodu: 30,
      tedarikci_tipi: 1,
      gtip: 5,
      yakinlik: 4,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 7,
          worker: 20,
          code: 'gosterge',
          location: 'Ankara',
          sektor: 'Teknoloji',
          description: 'Tekno Danışmanlar, en son bilgisayar teknolojileri hakkında uzmanlaşmış bir danışmanlık şirketidir.',
        },
      ],
    },
    {
      id: 81,
      name: 'Çocuk Giyim Mağazası',
      sektor: 3,
      category: 'Perakende',
      tp: 3,
      ify: 2,
      company: 'Minik Moda',
      nace_kodu: 12,
      tedarikci_tipi: 1,
      gtip: 3,
      yakinlik: 2,
      chart: true,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 3,
          worker: 8,
          code: 'gosterge',
          location: 'İzmir',
          sektor: 'Perakende',
          description: 'Minik Moda, çocuklar için en şık ve rahat giyim ürünlerini sunan bir mağazadır.',
        },
      ],
    },
    {
      id: 82,
      name: 'Yapı Malzemeleri Üretimi',
      sektor: 2,
      category: 'İnşaat',
      tp: 4,
      ify: 1,
      company: 'Yapıstar',
      nace_kodu: 8,
      tedarikci_tipi: 1,
      gtip: 4,
      yakinlik: 3,
      chart: true,
      group: true,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 6,
          worker: 12,
          code: 'gosterge',
          location: 'Bursa',
          sektor: 'İnşaat',
          description: 'Yapıstar, inşaat sektörü için yüksek kaliteli yapı malzemeleri üreten bir şirkettir.',
        },
      ],
    },
    {
      id: 83,
      name: 'Parfüm Üreticisi',
      sektor: 4,
      category: 'Kozmetik',
      tp: 5,
      ify: 4,
      company: 'Parfüm Dünyası',
      nace_kodu: 15,
      tedarikci_tipi: 2,
      gtip: 6,
      yakinlik: 5,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 8,
          worker: 18,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Kozmetik',
          description: 'Parfüm Dünyası, benzersiz ve kalıcı kokular üreten bir parfüm üreticisidir.',
        },
      ],
    },
    {
      id: 84,
      name: 'Hububat Ticareti',
      sektor: 6,
      category: 'Gıda',
      tp: 3,
      ify: 1,
      company: 'Hububat Güven',
      nace_kodu: 20,
      tedarikci_tipi: 1,
      gtip: 7,
      yakinlik: 4,
      chart: false,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 4,
          worker: 10,
          code: 'gosterge',
          location: 'Konya',
          sektor: 'Gıda',
          description: 'Hububat Güven, kaliteli hububat ticareti konusunda uzmanlaşmış bir şirkettir.',
        },
      ],
    },
    {
      id: 85,
      name: 'Yapay Zeka Çözümleri',
      sektor: 5,
      category: 'Teknoloji',
      tp: 4,
      ify: 1,
      company: 'ZekaTech',
      nace_kodu: 30,
      tedarikci_tipi: 1,
      gtip: 5,
      yakinlik: 3,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 7,
          worker: 20,
          code: 'gosterge',
          location: 'Ankara',
          sektor: 'Teknoloji',
          description: 'ZekaTech, işletmeler için yapay zeka tabanlı çözümler sunan bir teknoloji şirketidir.',
        },
      ],
    },
    {
      id: 86,
      name: 'Çiçekçi',
      sektor: 3,
      category: 'Perakende',
      tp: 2,
      ify: 3,
      company: 'Gül Bahçesi',
      nace_kodu: 14,
      tedarikci_tipi: 1,
      gtip: 3,
      yakinlik: 2,
      chart: false,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 2,
          worker: 5,
          code: 'gosterge',
          location: 'Ankara',
          sektor: 'Perakende',
          description: 'Gül Bahçesi, çiçeklerle dolu güzel bir bahçeden ilham alan bir çiçekçidir.',
        },
      ],
    },
    {
      id: 87,
      name: 'Yatırım Danışmanlığı',
      sektor: 7,
      category: 'Finans',
      tp: 4,
      ify: 1,
      company: 'Birikim Danışmanlar',
      nace_kodu: 25,
      tedarikci_tipi: 1,
      gtip: 8,
      yakinlik: 4,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 5,
          worker: 12,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Finans',
          description: 'Birikim Danışmanlar, yatırım konusunda uzmanlaşmış bir finans danışmanlık şirketidir.',
        },
      ],
    },
    {
      id: 88,
      name: 'Otomobil Tamiratı',
      sektor: 8,
      category: 'Otomotiv',
      tp: 3,
      ify: 2,
      company: 'Hızlı Tamirat',
      nace_kodu: 17,
      tedarikci_tipi: 1,
      gtip: 9,
      yakinlik: 3,
      chart: false,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 4,
          worker: 8,
          code: 'gosterge',
          location: 'Ankara',
          sektor: 'Otomotiv',
          description: 'Hızlı Tamirat, hızlı ve güvenilir otomobil tamirat hizmetleri sunan bir işletmedir.',
        },
      ],
    },
    {
      id: 89,
      name: 'Giyim Üreticisi',
      sektor: 3,
      category: 'Tekstil',
      tp: 5,
      ify: 1,
      company: 'Moda Tekstil',
      nace_kodu: 13,
      tedarikci_tipi: 2,
      gtip: 10,
      yakinlik: 4,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 6,
          worker: 15,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Tekstil',
          description: 'Moda Tekstil, son moda giyim ürünleri üreten bir tekstil üreticisidir.',
        },
      ],
    },
    {
      id: 90,
      name: 'Yiyecek Paketleme',
      sektor: 1,
      category: 'Gıda',
      tp: 3,
      ify: 3,
      company: 'Lezzet Paket',
      nace_kodu: 9,
      tedarikci_tipi: 1,
      gtip: 4,
      yakinlik: 2,
      chart: true,
      group: false,
      users: false,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 3,
          worker: 10,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Gıda',
          description: 'Lezzet Paket, enfes yiyecekleri güvenli bir şekilde paketleyen bir şirkettir.',
        },
      ],
    },
    {
      id: 91,
      name: 'Eğlence Merkezi',
      sektor: 10,
      category: 'Eğlence',
      tp: 4,
      ify: 2,
      company: 'Eğlence Dünyası',
      nace_kodu: 22,
      tedarikci_tipi: 1,
      gtip: 11,
      yakinlik: 3,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 5,
          worker: 15,
          code: 'gosterge',
          location: 'Ankara',
          sektor: 'Eğlence',
          description: 'Eğlence Dünyası, keyifli zamanlar geçirmeniz için birçok eğlence seçeneği sunan bir merkezdir.',
        },
      ],
    },
    {
      id: 92,
      name: 'Temizlik Malzemeleri Üretimi',
      sektor: 2,
      category: 'Kimya',
      tp: 5,
      ify: 4,
      company: 'Saf Temizlik',
      nace_kodu: 7,
      tedarikci_tipi: 2,
      gtip: 12,
      yakinlik: 5,
      chart: true,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 8,
          worker: 20,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Kimya',
          description: 'Saf Temizlik, kaliteli temizlik malzemeleri üreten bir kimya şirketidir.',
        },
      ],
    },
    {
      id: 93,
      name: 'Moda Tasarımı',
      sektor: 3,
      category: 'Tekstil',
      tp: 3,
      ify: 3,
      company: 'Moda Vizyon',
      nace_kodu: 16,
      tedarikci_tipi: 1,
      gtip: 13,
      yakinlik: 2,
      chart: false,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 4,
          worker: 8,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Tekstil',
          description: 'Moda Vizyon, son moda tasarımlar ve giyim ürünleri sunan bir moda tasarım şirketidir.',
        },
      ],
    },
    {
      id: 94,
      name: 'Gıda Toptancısı',
      sektor: 1,
      category: 'Gıda',
      tp: 4,
      ify: 1,
      company: 'Toptan Lezzet',
      nace_kodu: 10,
      tedarikci_tipi: 1,
      gtip: 14,
      yakinlik: 3,
      chart: false,
      group: true,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 6,
          worker: 12,
          code: 'gosterge',
          location: 'İzmir',
          sektor: 'Gıda',
          description: 'Toptan Lezzet, taze ve lezzetli gıda ürünlerini toptan satan bir işletmedir.',
        },
      ],
    },
    {
      id: 95,
      name: 'Mimari Tasarım Ofisi',
      sektor: 11,
      category: 'İnşaat',
      tp: 4,
      ify: 2,
      company: 'Mimari Vizyon',
      nace_kodu: 8,
      tedarikci_tipi: 1,
      gtip: 15,
      yakinlik: 3,
      chart: true,
      group: true,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 7,
          worker: 15,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'İnşaat',
          description: 'Mimari Vizyon, estetik ve işlevselliği birleştiren benzersiz mimari tasarımlar sunan bir ofistir.',
        },
      ],
    },
    {
      id: 96,
      name: 'Organik Kozmetik Üretimi',
      sektor: 4,
      category: 'Kozmetik',
      tp: 3,
      ify: 1,
      company: 'Doğal Güzellik',
      nace_kodu: 15,
      tedarikci_tipi: 2,
      gtip: 16,
      yakinlik: 2,
      chart: false,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 4,
          worker: 10,
          code: 'gosterge',
          location: 'Antalya',
          sektor: 'Kozmetik',
          description: 'Doğal Güzellik, organik ve doğal kozmetik ürünleri üreten bir şirkettir.',
        },
      ],
    },
    {
      id: 97,
      name: 'Oyun Geliştirme Stüdyosu',
      sektor: 5,
      category: 'Teknoloji',
      tp: 4,
      ify: 3,
      company: 'Oyun Dünyası',
      nace_kodu: 31,
      tedarikci_tipi: 1,
      gtip: 17,
      yakinlik: 4,
      chart: true,
      group: false,
      users: true,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 5,
          worker: 12,
          code: 'gosterge',
          location: 'Ankara',
          sektor: 'Teknoloji',
          description: 'Oyun Dünyası, eğlenceli ve yenilikçi video oyunları geliştiren bir stüdyodur.',
        },
      ],
    },
    {
      id: 98,
      name: 'Otomobil Yedek Parça Mağazası',
      sektor: 8,
      category: 'Otomotiv',
      tp: 4,
      ify: 2,
      company: 'Yedek Parça Depo',
      nace_kodu: 17,
      tedarikci_tipi: 1,
      gtip: 18,
      yakinlik: 3,
      chart: false,
      group: false,
      users: true,
      pin: false,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 4,
          worker: 10,
          code: 'gosterge',
          location: 'İstanbul',
          sektor: 'Otomotiv',
          description: 'Yedek Parça Depo, otomobiller için yedek parçalar sunan bir mağazadır.',
        },
      ],
    },
    {
      id: 99,
      name: 'Ev Temizlik Hizmetleri',
      sektor: 2,
      category: 'Hizmetler',
      tp: 3,
      ify: 3,
      company: 'Temiz Ev',
      nace_kodu: 7,
      tedarikci_tipi: 1,
      gtip: 19,
      yakinlik: 2,
      chart: true,
      group: true,
      users: false,
      pin: true,
      companyInfo: [
        {
          name: 'Hakkımızda',
          ciro: 3,
          worker: 8,
          code: 'gosterge',
          location: 'İzmir',
          sektor: 'Hizmetler',
          description: 'Temiz Ev, ev temizliği hizmetleri sunan bir şirkettir ve evlerinizi tertemiz yapar.',
        },
      ],
    },
  ]
  constructor() { }
}
