import { CompanyTypes, UserRoles } from "../modules/auth/models/user-company.model";

export class UsersTable {
  public static users: any = [
    {
      id: 1,
      username: 'admin',
      password: 'demo',
      email: 'admin@ankabeta.com',
      authToken: 'auth-token-8f3ae836da744329a6f93bf20594b5cc',
      refreshToken: 'auth-token-f8c137a2c98743f48b643e71161d90aa',
      roles: UserRoles.Admin, // Administrator
      pic: './assets/media/avatars/300-1.jpg',
      fullname: 'Hasan Oruç',
      firstname: 'Hasan',
      lastname: 'Oruç',
      companyName: 'AnkaBeta',
      country:'Türkiye',
      phone: '531111111',
      language: 'tr',
      timeZone: 'International Date Line West',
      userCompanies:[{
        company: { id: 7, name: 'ADMIN',img : {url:'./assets/media/logos/kosgeb.png'}, type: CompanyTypes.ADMIN},
        roles:[UserRoles.Admin],
        occupation: 'Genel Müdür',
      }],
      website: 'https://ankabeta.com.tr',
      selectedCompany:'',
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromKeenthemes: {
          newsAboutKeenthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfKeen: false,
          thingsYouMissedSindeYouLastLoggedIntoKeen: true,
          newsAboutMetronicOnPartnerProductsAndOtherServices: true,
          tipsOnMetronicBusinessProducts: true,
        },
      },
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      address: {
        addressLine: 'L-12-20 Vertex, Cybersquare',
        city: 'San Francisco',
        state: 'California',
        postCode: '45000',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/admin',
        facebook: 'https://facebook.com/admin',
        twitter: 'https://twitter.com/admin',
        instagram: 'https://instagram.com/admin',
      },
    },
    {
      id: 2,
      username: 'kosgebAdmin',
      password: 'demo',
      email: 'admin@kosgeb.com',
      authToken: 'auth-token-6829bba69dd3421d8762-991e9e806dbf',
      refreshToken: 'auth-token-f8e4c61a318e4d618b6c199ef96b9e55',
      roles: UserRoles.KosgebAdmin, // Manager
      pic: './assets/media/avatars/300-6.jpg',
      fullname: 'Anka Beta',
      firstname: 'Anka',
      lastname: 'Beya',
      occupation: 'KOSGEB Müdürü',
      companyName: 'KOSGEB',
      country:'Türkiye',
      phone: '456669067891',
      language: 'en',
      timeZone: 'International Date Line West',
      userCompanies:[{
        company: { id: 6, name: 'KOSGEB',img : {url:'./assets/media/logos/kosgeb.png'}, type: CompanyTypes.KOSGEB},
        roles:[UserRoles.KosgebAdmin],
        occupation: 'Genel Müdür',
      }],
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromKeenthemes: {
          newsAboutKeenthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfKeen: false,
          thingsYouMissedSindeYouLastLoggedIntoKeen: true,
          newsAboutMetronicOnPartnerProductsAndOtherServices: true,
          tipsOnMetronicBusinessProducts: true,
        },
      },
      address: {
        addressLine: 'T.C. Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı Hacı Bayram Mah. İstanbul Cad. No: 3206050',
        city: 'ANKARA',
        state: 'Türkiye',
        postCode: '85012',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/user',
        facebook: 'https://facebook.com/user',
        twitter: 'https://twitter.com/user',
        instagram: 'https://instagram.com/user',
      },
    },
    {
      id: 3,
      username: 'KOSGEBUser',
      password: 'demo',
      email: 'user@kosgeb.com',
      authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
      refreshToken: 'auth-token-c999ccfe74aa40d0aa1a64c5e620c1a5',
      roles: UserRoles.KosgebUser, // Guest
      pic: './assets/media/avatars/300-20.jpg',
      fullname: 'Mehmet Yılmaz',
      firstname: 'Mehmet',
      lastname: 'Yılmaz',
      occupation: 'KOSGEB Kullanıcısı',
      country:'Türkiye',
      companyName: 'KOSGEB',
      phone: '456669067892',
      language: 'en',
      timeZone: 'International Date Line West',
      userCompanies:[{
        company: { id: 6, name: 'KOSGEB',img : {url:'./assets/media/logos/kosgeb.png'}, type: CompanyTypes.KOSGEB},
        roles:[UserRoles.KosgebUser],
        occupation: 'Genel Müdür',
      }],
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromKeenthemes: {
          newsAboutKeenthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfKeen: false,
          thingsYouMissedSindeYouLastLoggedIntoKeen: true,
          newsAboutMetronicOnPartnerProductsAndOtherServices: true,
          tipsOnMetronicBusinessProducts: true,
        },
      },
      address: {
        addressLine: 'T.C. Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı Hacı Bayram Mah. İstanbul Cad. No: 3206050',
        city: 'ANKARA',
        state: 'Türkiye',
        postCode: '85012',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/guest',
        facebook: 'https://facebook.com/guest',
        twitter: 'https://twitter.com/guest',
        instagram: 'https://instagram.com/guest',
      },
    },
    {
      id: 4,
      username: 'Kullanıcı',
      password: 'demo',
      email: 'kullanici@demo.com',
      authToken: 'auth-token-d2dff7b82f784de845b60964abbe45b9',
      refreshToken: 'auth-token-c999ccfe74aa60d0aa1a64c5e620c1a5',
      roles:  UserRoles.User, // Guest
      pic: './assets/media/avatars/300-20.jpg',
      fullname: 'Manu G',
      firstname: 'Manu',
      lastname: 'Ginobili',
      occupation: 'CFO',
      country:'Türkiye',
      companyName: 'Keenthemes',
      phone: '456669067892',
      userCompanies:[{
        company: { id: 2, name: 'BMW',img : {url:'./assets/media/logos/bmw.png'}, type: CompanyTypes.BI},
        roles:[1],
        occupation: 'Genel Müdür',
      },
      {
        company: { id: 1, name: 'Ankabeta',img : {url:'./assets/media/logos/ankabeta-logo.png'}, type: CompanyTypes.KOBI},
        roles:[1],
        occupation: 'CEO',
      },
      {
        company: { id: 5, name: 'Odak Teknoloji',img : {url:'./assets/media/logos/logo1.png'}, type: CompanyTypes.KOBI},
        roles:[3],
        occupation: 'Pazarlama Uzmanı',
      }],
      language: 'en',
      timeZone: 'International Date Line West',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromKeenthemes: {
          newsAboutKeenthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfKeen: false,
          thingsYouMissedSindeYouLastLoggedIntoKeen: true,
          newsAboutMetronicOnPartnerProductsAndOtherServices: true,
          tipsOnMetronicBusinessProducts: true,
        },
      },
      address: {
        addressLine: 'Martı Cd. Balık Sk. No:23',
        city: 'Balıkesir',
        state: 'Türkiye',
        postCode: '85012',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/guest',
        facebook: 'https://facebook.com/guest',
        twitter: 'https://twitter.com/guest',
        instagram: 'https://instagram.com/guest',
      },
    },
    {
      id: 5,
      username: 'Kullanıcı2',
      password: 'demo',
      email: 'kullanici2@demo.com',
      authToken: 'auth-token-d2dff7b82f7843e584b60964abbe45b9',
      refreshToken: 'auth-token-c999ccfe74aa6540aa1a64c5e620c1a5',
      roles: UserRoles.User, // Guest
      pic: './assets/media/avatars/300-20.jpg',
      fullname: 'Manu G',
      firstname: 'Manu',
      lastname: 'Ginobili',
      occupation: 'CFO',
      country:'Türkiye',
      companyName: 'Keenthemes',
      phone: '456669067892',
      language: 'en',
      timeZone: 'International Date Line West',
      userCompanies:[{
        company: { id: 2, name: 'ISUZU',img : {url:'./assets/media/logos/isuzu.png'}, type: CompanyTypes.BI},
        roles:[1],
        occupation: 'Genel Müdür',
      },
      {
        company: { id: 1, name: 'Ulak A.Ş',img : {url:'./assets/media/logos/logo2.png'}, type: CompanyTypes.KOBI},
        roles:[1],
        occupation: 'CEO',
      },
      {
        company: { id: 5, name: 'Odak Teknoloji',img : {url:'./assets/media/logos/logo1.png'}, type: CompanyTypes.KOBI},
        roles:[3],
        occupation: 'Pazarlama Uzmanı',
      }],
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromKeenthemes: {
          newsAboutKeenthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfKeen: false,
          thingsYouMissedSindeYouLastLoggedIntoKeen: true,
          newsAboutMetronicOnPartnerProductsAndOtherServices: true,
          tipsOnMetronicBusinessProducts: true,
        },
      },
      address: {
        addressLine: 'Tarihler Cd. Ulak Sk. No:23',
        city: 'İstanbul',
        state: 'Türkiye',
        postCode: '85012',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/guest',
        facebook: 'https://facebook.com/guest',
        twitter: 'https://twitter.com/guest',
        instagram: 'https://instagram.com/guest',
      },
    },
  ];

  public static tokens: any = [
    {
      id: 1,
      authToken: 'auth-token-' + Math.random(),
      refreshToken: 'auth-token-' + Math.random(),
    },
  ];
}
